// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Autonomous.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Autonomous::Autonomous(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Autonomous::Initialize() {
	Robot::timer->Reset();	//sets timer to 0
}

// Called repeatedly when this Command is scheduled to run
void Autonomous::Execute() {
	while (Robot::timer->Get() > 2) {	//moves forward for 2 seconds
		Robot::driveTrain->ArcadeDrive(0, 1);
	}

	shoot_ptr->Start();	//calls the shoot command
}

// Make this return true when this Command no longer needs to run execute()
bool Autonomous::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void Autonomous::End() {
	Robot::driveTrain->Stop();
	Robot::timer->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Autonomous::Interrupted() {

}
