// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Up_Down_Pivot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Up_Down_Pivot::Up_Down_Pivot(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::pivot.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Up_Down_Pivot::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void Up_Down_Pivot::Execute() {
	Robot::pivot->Up_Down();
}

// Make this return true when this Command no longer needs to run execute()
bool Up_Down_Pivot::IsFinished() {
    return true;	//returns true as it only needs to be done once
}

// Called once after isFinished returns true
void Up_Down_Pivot::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Up_Down_Pivot::Interrupted() {

}
