// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"
#include "Xbox360_Controller.h"

class OI {
private:
	std::shared_ptr<XBOX360_Controller> _operator;
	std::shared_ptr<XBOX360_Controller> _driver;
	//creates shared pointers to the operator and driver controllers

public:
	OI();	//the constructor
			//called in the Robot.cpp file
			//"oi.reset(new OI());"

	std::shared_ptr<XBOX360_Controller> getDriver();
	std::shared_ptr<XBOX360_Controller> getOperator();
	//these functions returns the shared pointer of the controllers
};

#endif
